repos:
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      args: [--preview]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.252'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
